---
- hosts: all
  remote_user: ubuntu
  tasks:
    - name: delete old directory
      file:
        path: ~/CSE_356_HW1
        state: absent
    - name: clone server
      command: git clone https://github.com/jerchu/CSE_356_HW1.git
      args:
        chdir: ~
    - name: install pip3
      apt: 
        name: python3-pip
      become: yes
      become_method: sudo
    - name: install Flask
      apt:
        name: python3-flask
      become: yes
      become_method: sudo
    - name: install Gunicorn
      apt:
        name: gunicorn
      become: yes
      become_method: sudo
    - name: start server
      gunicorn:
        app: 'server'
        chdir: /home/ubuntu/CSE_356_HW1
      become: yes
      become_method: sudo

