---
- hosts: all
  remote_user: ubuntu
  tasks:
    - name: kill old server
      shell: "test -e ~/CSE_356_HW1/srv_pid.txt && sudo kill $(cat srv_pid.txt)"
      ignore_errors: True
      args:
        chdir: ~/CSE_356_HW1
    - name: delete old directory
      file:
        path: ~/CSE_356_HW1
        state: absent
    - name: clone server
      command: git clone https://github.com/jerchu/CSE_356_HW1.git
      args:
        chdir: ~
    - name: install pip3
      apt: 
        name: python3-pip
      become: yes
      become_method: sudo
    - name: install Flask
      apt:
        name: python3-flask
      become: yes
      become_method: sudo
    - name: start server and save pid
      shell: "nohup python3 server.py & echo $! > srv_pid.txt"
      args:
        chdir: /home/ubuntu/CSE_356_HW1
      become: yes
      become_method: sudo
      