---
- hosts: all
  remote_user: ubuntu
  tasks:
    - name: delete old directory
      file:
        path: ~/CSE_356_HW1
        state: absent
    - name: clone server
      command: git clone https://github.com/jerchu/CSE_356_HW1.git
      args:
        chdir: ~
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
      become: yes
      become_method: sudo
    - name: install pip3
      apt: 
        name: python3-pip
        update_cache: yes
      become: yes
      become_method: sudo
    - name: install Flask
      apt:
        name: python3-flask
      become: yes
      become_method: sudo
    - name: install Gevent
      shell: pip3 install gevent --user
    - name: copy conf file
      copy: src=/home/ubuntu/server/FlaskApp.conf dest=/etc/apache2/sites-available/server.conf remote_src=yes
    - name: start server
      command: a2ensite server
      args:
        creates: /etc/apache2/sites-enabled/server.conf
    - name: restart apache
      service: name=apache2 state=restarted
      